[profile.default]
src = "vendor"
out = "out"
libs = ["lib"]

# Skip submodule initialization for x402 contracts
[profile.x402]
src = "contracts"
out = "out"
libs = ["lib/openzeppelin-contracts"]
remappings = ["@openzeppelin/=lib/openzeppelin-contracts/"]
no_auto_detect_git = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
